WashingtonChameleons/WashingtonChameleons/Controllers/ActiveCarriersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WashingtonChameleons.Models;
using PagedList;
using SmartBreadcrumbs.Attributes;

namespace WashingtonChameleons.Controllers
{
    public class ActiveCarriersController : Controller
    {
        private readonly WashingtonContext _context;

        public ActiveCarriersController(WashingtonContext context)
        {
            _context = context;
        }

        // GET: ActiveCarriers
        [Breadcrumb("Active Carriers")]
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var companies = from c in _context.ActiveCarriers
                            select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                companies = companies.Where(c => c.LegalName.Contains(searchString));
            }


            companies = companies.OrderBy(c => c.LegalName);

            int pageSize = 50;
            return View(await PaginatedList<Models.ActiveCarriers>.CreateAsync(companies.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: ActiveCarriers/Details/5
        [Breadcrumb("Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activeCarriers = await _context.ActiveCarriers
                .FirstOrDefaultAsync(m => m.DotNumber == id);
            if (activeCarriers == null)
            {
                return NotFound();
            }

            return View(activeCarriers);
        }

    }
}

WashingtonChameleons/WashingtonChameleons/Controllers/ChameleonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WashingtonChameleons.Models;
using PagedList;
using SmartBreadcrumbs.Attributes;

namespace WashingtonChameleons.Controllers
{
    public class ChameleonController : Controller
    {
        private readonly WashingtonContext _context;

        public ChameleonController(WashingtonContext context)
        {
            _context = context;
        }

        // GET: Chameleon
        [Breadcrumb("Potential Chameleon Companies")]
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? pageNumber, int? minRating)
        {          

            if (searchString != null)
            {
                pageNumber = 1;

            } else
            {
                searchString = currentFilter;
            }

            var companies = from c in _context.ChameleonTable
                            select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                companies = companies.Where(c => c.CurrentName.Contains(searchString) || c.FormerName.Contains(searchString));
                ViewData["CurrentFilter"] = searchString;
            }

            if (minRating != null)
            {
                companies = companies.Where(c => c.ConfidenceLevel >= minRating);
                ViewData["MinRating"] = minRating;
            } else
            {
                ViewData["MinRating"] = 1;
            }


            companies = companies.OrderBy(c => c.CurrentName);

            int pageSize = 12;
            return View(await PaginatedList<ChameleonTable>.CreateAsync(companies.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Chameleon/Details/5
        [Breadcrumb("Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chameleonTable = await _context.ChameleonTable
                .FirstOrDefaultAsync(m => m.ChameleonId == id);
            if (chameleonTable == null)
            {
                return NotFound();
            }

            /* Get Potential Chameleon Company */
            var CurrentCompany = from c in _context.ActiveCarriers.Where(c => c.Latitude.Equals(chameleonTable.Latitude) && c.Longitude.Equals(chameleonTable.Longitude))
                                 select c;

            ViewBag.CurrentDotNumber = CurrentCompany.First().DotNumber;
            ViewBag.CurrentDrivers = CurrentCompany.First().DriverTotal;

            /* View Original */
            var OriginalCompany = from c in _context.Carriers.Where(c => c.Latitude.Equals(chameleonTable.Latitude) && c.Longitude.Equals(chameleonTable.Longitude))
                                  select c;


            ViewBag.OCDotNumber = OriginalCompany.First().DotNumber;
            ViewBag.OCName = OriginalCompany.First().CarrierName;
            ViewBag.OCStreet = OriginalCompany.First().StreetAddress;
            ViewBag.OCCity = OriginalCompany.First().City;
            ViewBag.OCState = OriginalCompany.First().StateAddress;
            ViewBag.OCZip = OriginalCompany.First().Zipcode;
            ViewBag.OCOOSReason = OriginalCompany.First().OosReason;

            return View(chameleonTable);
        }

        private bool ChameleonTableExists(int id)
        {
            return _context.ChameleonTable.Any(e => e.ChameleonId == id);
        }
    }
}

WashingtonChameleons/WashingtonChameleons/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Washington Chameleons</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.custom.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap.custom.min.css"
              
              crossorigin="anonymous"
              integrity="" />
    </environment>


    @RenderSection("Mapquest", required: false)
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/8792d2d45f.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-secondary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Washington Chameleons</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Chameleon" asp-action="Index">Potential Chameleon Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActiveCarriers" asp-action="Index">Active Carriers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="container">
            <breadcrumb></breadcrumb>
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>&copy; 2020 - WashingtonChameleons</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>